# -*- coding: utf-8 -*-
"""Untitled3.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VWFS9xGYRFTtqs2K1aHiH8-xu0KW_pAF
"""

# global variable and module-level var
light = "Green"
speed = 60

#class Vehicle
class Vehicle:
    def start_engine(self):
      msg = "Engine started."
      print(msg)

#+Car that inherits from Vehicle
class Car(Vehicle):
    def __init__(self, make):
        self.make = make

    def start_engine(self):
        msg = "Car engine started."
        print(msg)

#++Bike that inherits from Vehicle
class Bike(Vehicle):
    def __init__(self, bike_type):
        self.type = bike_type

    def start_engine(self):
        msg = "Bike engine started."
        print(msg)

# Making instances of Car and Bike
my_car = Car("Honda")
my_bike = Bike("Road")

# Putting the instances in a list
vehicles = [my_car, my_bike]


# ________Starting the engines___________
my_car.start_engine()
my_bike.start_engine()

print("Light is :", light)
print("Speed limit is:", speed, "km/h")
print("The car's make is:", my_car.make)
print("The bike's type is:", my_bike.type)